### ISSUE TITLE
Incompatible with numpy 1.24

### ISSUE THREAD

**Issue by mscheltienne** [xdf-modules/pyxdf#86]
`pyxdf` does not work with numpy 1.24. It works with numpy up to `1.23`.
The 1.24 version raises:

```
  File ~/pyvenv/mscheltienne/eeg-flow/lib/python3.10/site-packages/eeg_flow/io.py:32 in load_xdf
    streams, _ = pyxdf.load_xdf(fname)

  File ~/pyvenv/mscheltienne/eeg-flow/lib/python3.10/site-packages/pyxdf/pyxdf.py:303 in load_xdf
    temp[StreamId] = StreamData(hdr)

  File ~/pyvenv/mscheltienne/eeg-flow/lib/python3.10/site-packages/pyxdf/pyxdf.py:37 in __init__
    string=np.object,

  File ~/pyvenv/mscheltienne/eeg-flow/lib/python3.10/site-packages/numpy/__init__.py:284 in __getattr__
    raise AttributeError("module {!r} has no attribute "

AttributeError: module 'numpy' has no attribute 'object'
```
